### ISSUE TITLE
Footer: menu order and placement below 990px breakpoint

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#104]
The footer menu shifts slightly out of order below 990px:

![image](https://user-images.githubusercontent.com/1140183/157765530-7463d5ce-2155-4ed7-b989-6bc005dc9a31.png)

I'm not sure if that placement is correct, but it feels like it should fit on the first row at this breakpoint.

**Comment by nienn** [comment]
SUI uses a hardcoded `width: 50% !important` for the `.doubling.grid` columns bellow viewport `992px`. This forces the 50% width without any of the usual flexibility from flexbox. So the placement is in accordance with the expected behaviour from SUI.

IMO, however, the footer is a custom element with very specific requirements dictated by each site. It should not be dependant entirely on the framework native behaviours.
I believe the footer should be styled with custom CSS and that would both simplify future editing at the same time as it gives finer control over behaviours.

**Comment by agjohnson** [comment]
Without doubling, it looks like this:

![image](https://user-images.githubusercontent.com/1140183/158247656-6554a83f-18af-4729-aefd-d2efd7ee5bcb.png)

That seems better than with doubling, even if the text field is squashed.

**Comment by nienn** [comment]
So my feeling here is that the columns are very unbalanced --the white space left by the narrower columns leaves them hanging in heavy contrast with the wider first column.

Using 3 columns with fixed widths works technically, it's just not visually appealing and leaves a messy feeling.

**Comment by agjohnson** [comment]
The desktop view size is already using 3 columns though, so nothing really changes by dropping doubling. It does prevent the 3rd column from stacking under the 1st, which seems definitively worse.

I think the answer is removing doubling and tuning the content in the columns to help match the vertical footprint of the first column.
